safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: ZZP's Site
host: zzppbs.githup.io
desc: 方向胜于速度.

custom:
    category:
        default: corlorful life 
        another: Another 
    categories:
      - name:  default
        title: corlorful life

      - name:  another
        title: Another

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Zhou Zhipeng
        email: zzpzhouzhipeng@gmail.com
        disqus: zzpp              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: zzpzhouzhipeng                 # GitHub账号
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
